language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ptriantafyll/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ptriantafyll/docker-react npm run test

deploy:
  provide: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-486544480974"
  bucker_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY 
  secret_access_key: $AWS_SECRET_KEY