language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ptriantafyll/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true ptriantafyll/docker-react npm run test